version: '3.8'

services:
  mafl:
    container_name: mafl
    image: hywax/mafl
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - ./config/config.yml:/app/data/config.yml

  mafl-service-discovery:
    image: lracz/mafl-service-discovery:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./config:/app/config
    restart: unless-stopped
